version: '3.8'

services:

  inatrace-frontend:
    image: ${IMAGE_NAME}:${TAG}
    container_name: inatrace-fe
    networks:
      - frontend
    ports:
      - "80:80"
    restart: always

networks:
  frontend:
    name: inatrace-frontend-network
